uv run main.py pull https://www.youtube.com/@TheComputerGraveyard
uv run main.py pull https://www.youtube.com/@CtrlAltFailYT
uv run main.py pull https://www.youtube.com/@techdisctrict
uv run main.py pull https://www.youtube.com/@OnceEverywhere-m5m
uv run main.py pull https://www.youtube.com/@Tech-Of-History
uv run main.py pull https://www.youtube.com/@TheHiddenPartsofHistory
uv run main.py pull https://www.youtube.com/@theeconomyhistorian/videos
uv run main.py pull https://www.youtube.com/@PrometheanAction/videos
uv run main.py pull https://www.youtube.com/@PrometheanOverviews/videos
uv run main.py pull https://www.youtube.com/@AmericaUncovered/videos
uv run main.py pull https://www.youtube.com/@BillWhittleChannel/videos
uv run main.py pull https://www.youtube.com/@ChinaUncensored/videos
uv run main.py pull https://www.youtube.com/@ChrisWillx/videos
uv run main.py pull https://www.youtube.com/@ClimateDN/videos
uv run main.py pull https://www.youtube.com/@DailySignal/videos
uv run main.py pull https://www.youtube.com/@DrJordanBPetersonClips/videos
uv run main.py pull https://www.youtube.com/@EconomyMeetHistory/videos
uv run main.py pull https://www.youtube.com/@EmergingVoicesStudio/videos
uv run main.py pull https://www.youtube.com/@Europe-Informed-Connected/videos
uv run main.py pull https://www.youtube.com/@GDiesen1/videos
uv run main.py pull https://www.youtube.com/@Maxinomics/videos
uv run main.py pull https://www.youtube.com/@MichaelKnowles/videos
uv run main.py pull https://www.youtube.com/@NewDiscourses/videos
uv run main.py pull https://www.youtube.com/@SimonDixon21/videos
uv run main.py pull https://www.youtube.com/@StephenGardner1/videos
uv run main.py pull https://www.youtube.com/@YAFTV/videos
uv run main.py pull https://www.youtube.com/@axiomfounder/videos
uv run main.py pull https://www.youtube.com/@chillfinancialhistorian/videos
uv run main.py pull https://www.youtube.com/@code4AI/videos
uv run main.py pull https://www.youtube.com/@diggingintochina/videos
uv run main.py pull https://www.youtube.com/@matthew_berman/videos
uv run main.py pull https://www.youtube.com/@prageru/videos
uv run main.py pull https://www.youtube.com/@truthrevoltoriginals9835/videos
uv run main.py pull https://www.youtube.com/@victordavishanson7273/videos
uv run main.py pull https://www.youtube.com/@X22Report-y5y/videos
uv run main.py organize
